package wei.mark.standout.constants;

public class StandOutFlags {
    public static final int FLAG_ADD_FUNCTIONALITY_ALL_DISABLE;
    public static final int FLAG_ADD_FUNCTIONALITY_DROP_DOWN_DISABLE;
    public static final int FLAG_ADD_FUNCTIONALITY_RESIZE_DISABLE;
    public static final int FLAG_BODY_MOVE_ENABLE;
    public static final int FLAG_DECORATION_CLOSE_DISABLE;
    public static final int FLAG_DECORATION_MAXIMIZE_DISABLE;
    public static final int FLAG_DECORATION_MOVE_DISABLE;
    public static final int FLAG_DECORATION_RESIZE_DISABLE;
    public static final int FLAG_DECORATION_SYSTEM;
    public static final int FLAG_FIX_COMPATIBILITY_ALL_DISABLE;
    public static final int FLAG_WINDOW_ASPECT_RATIO_ENABLE;
    public static final int FLAG_WINDOW_BRING_TO_FRONT_ON_TAP;
    public static final int FLAG_WINDOW_BRING_TO_FRONT_ON_TOUCH;
    public static final int FLAG_WINDOW_EDGE_LIMITS_ENABLE;
    public static final int FLAG_WINDOW_FOCUSABLE_DISABLE;
    public static final int FLAG_WINDOW_FOCUS_INDICATOR_DISABLE;
    public static final int FLAG_WINDOW_HIDE_ENABLE;
    public static final int FLAG_WINDOW_PINCH_RESIZE_ENABLE;
    private static int flag_bit;

    static {
        flag_bit = 0;
        int i = flag_bit;
        flag_bit = i + 1;
        FLAG_DECORATION_SYSTEM = 1 << i;
        i = FLAG_DECORATION_SYSTEM;
        int i2 = flag_bit;
        flag_bit = i2 + 1;
        FLAG_DECORATION_CLOSE_DISABLE = i | (1 << i2);
        i = FLAG_DECORATION_SYSTEM;
        i2 = flag_bit;
        flag_bit = i2 + 1;
        FLAG_DECORATION_RESIZE_DISABLE = i | (1 << i2);
        i = FLAG_DECORATION_SYSTEM;
        i2 = flag_bit;
        flag_bit = i2 + 1;
        FLAG_DECORATION_MAXIMIZE_DISABLE = i | (1 << i2);
        i = FLAG_DECORATION_SYSTEM;
        i2 = flag_bit;
        flag_bit = i2 + 1;
        FLAG_DECORATION_MOVE_DISABLE = i | (1 << i2);
        i = flag_bit;
        flag_bit = i + 1;
        FLAG_BODY_MOVE_ENABLE = 1 << i;
        i = flag_bit;
        flag_bit = i + 1;
        FLAG_WINDOW_HIDE_ENABLE = 1 << i;
        i = flag_bit;
        flag_bit = i + 1;
        FLAG_WINDOW_BRING_TO_FRONT_ON_TOUCH = 1 << i;
        i = flag_bit;
        flag_bit = i + 1;
        FLAG_WINDOW_BRING_TO_FRONT_ON_TAP = 1 << i;
        i = flag_bit;
        flag_bit = i + 1;
        FLAG_WINDOW_EDGE_LIMITS_ENABLE = 1 << i;
        i = flag_bit;
        flag_bit = i + 1;
        FLAG_WINDOW_ASPECT_RATIO_ENABLE = 1 << i;
        i = flag_bit;
        flag_bit = i + 1;
        FLAG_WINDOW_PINCH_RESIZE_ENABLE = 1 << i;
        i = flag_bit;
        flag_bit = i + 1;
        FLAG_WINDOW_FOCUSABLE_DISABLE = 1 << i;
        i = flag_bit;
        flag_bit = i + 1;
        FLAG_WINDOW_FOCUS_INDICATOR_DISABLE = 1 << i;
        i = flag_bit;
        flag_bit = i + 1;
        FLAG_FIX_COMPATIBILITY_ALL_DISABLE = 1 << i;
        i = flag_bit;
        flag_bit = i + 1;
        FLAG_ADD_FUNCTIONALITY_ALL_DISABLE = 1 << i;
        i = flag_bit;
        flag_bit = i + 1;
        FLAG_ADD_FUNCTIONALITY_RESIZE_DISABLE = 1 << i;
        i = flag_bit;
        flag_bit = i + 1;
        FLAG_ADD_FUNCTIONALITY_DROP_DOWN_DISABLE = 1 << i;
    }
}
