package com.foxit.uiextensions.utils;

import android.app.Activity;
import android.content.Intent;
import android.net.Uri;
import android.support.v4.media.TransportMediator;
import com.foxit.sdk.common.Font;
import com.netspace.library.error.ErrorCode;
import com.netspace.library.servers.NanoHTTPD;
import com.netspace.library.threads.CheckNewVersionThread2;
import io.vov.vitamio.ThumbnailUtils;
import java.io.File;
import me.dm7.barcodescanner.zbar.BuildConfig;
import net.sqlcipher.database.SQLiteDatabase;
import okhttp3.internal.http.StatusLine;
import org.apache.http.HttpStatus;
import org.ksoap2.SoapEnvelope;
import org.kxml2.wap.Wbxml;

public class AppIntentUtil {
    public static final String[][] MIME_MapTable;

    public static void openFile(Activity act, String filePath) {
        Uri uri = Uri.parse("file://" + filePath);
        Intent intent = new Intent();
        intent.addFlags(SQLiteDatabase.CREATE_IF_NECESSARY);
        intent.setAction("android.intent.action.VIEW");
        int lastIndex = filePath.lastIndexOf(46);
        String type = getMIMEType(lastIndex >= 0 ? filePath.substring(lastIndex).toLowerCase() : "");
        intent.setDataAndType(uri, type);
        if (type.equals("*/*")) {
            act.startActivity(showOpenTypeDialog(filePath));
            return;
        }
        try {
            act.startActivity(intent);
        } catch (Exception e) {
            e.printStackTrace();
            act.startActivity(showOpenTypeDialog(filePath));
        }
    }

    public static Intent showOpenTypeDialog(String param) {
        Intent intent = new Intent();
        intent.addFlags(SQLiteDatabase.CREATE_IF_NECESSARY);
        intent.setAction("android.intent.action.VIEW");
        intent.setDataAndType(Uri.fromFile(new File(param)), "*/*");
        return intent;
    }

    public static String getMIMEType(String exp) {
        String str = "*/*";
        if (exp.length() < 1) {
            return str;
        }
        for (int i = 0; i < MIME_MapTable.length; i++) {
            if (exp.equals(MIME_MapTable[i][0])) {
                str = MIME_MapTable[i][1];
            }
        }
        return str;
    }

    static {
        r0 = new String[440][];
        r0[0] = new String[]{".3gp", "video/3gpp"};
        r0[1] = new String[]{".3gpp", "video/3gpp"};
        r0[2] = new String[]{".aac", "audio/x-mpeg"};
        r0[3] = new String[]{".amr", "audio/x-mpeg"};
        r0[4] = new String[]{".apk", "application/vnd.android.package-archive"};
        r0[5] = new String[]{".avi", "video/x-msvideo"};
        r0[6] = new String[]{".aab", "application/x-authoware-bin"};
        r0[7] = new String[]{".aam", "application/x-authoware-map"};
        r0[8] = new String[]{".aas", "application/x-authoware-seg"};
        r0[9] = new String[]{".ai", "application/postscript"};
        r0[10] = new String[]{".aif", "audio/x-aiff"};
        r0[11] = new String[]{".aifc", "audio/x-aiff"};
        r0[12] = new String[]{".aiff", "audio/x-aiff"};
        r0[13] = new String[]{".als", "audio/x-alpha5"};
        r0[14] = new String[]{".amc", "application/x-mpeg"};
        r0[15] = new String[]{".ani", "application/octet-stream"};
        r0[16] = new String[]{".asc", "text/plain"};
        r0[17] = new String[]{".asd", "application/astound"};
        r0[18] = new String[]{".asf", "video/x-ms-asf"};
        r0[19] = new String[]{".asn", "application/astound"};
        r0[20] = new String[]{".asp", "application/x-asap"};
        r0[21] = new String[]{".asx", " video/x-ms-asf"};
        r0[22] = new String[]{".au", "audio/basic"};
        r0[23] = new String[]{".avb", "application/octet-stream"};
        r0[24] = new String[]{".awb", "audio/amr-wb"};
        r0[25] = new String[]{".bcpio", "application/x-bcpio"};
        r0[26] = new String[]{".bld", "application/bld"};
        r0[27] = new String[]{".bld2", "application/bld2"};
        r0[28] = new String[]{".bpk", "application/octet-stream"};
        r0[29] = new String[]{".bz2", "application/x-bzip2"};
        r0[30] = new String[]{".bin", "application/octet-stream"};
        r0[31] = new String[]{".bmp", "image/bmp"};
        r0[32] = new String[]{".c", "text/plain"};
        r0[33] = new String[]{".class", "application/octet-stream"};
        r0[34] = new String[]{".conf", "text/plain"};
        r0[35] = new String[]{".cpp", "text/plain"};
        r0[36] = new String[]{".cal", "image/x-cals"};
        r0[37] = new String[]{".ccn", "application/x-cnc"};
        r0[38] = new String[]{".cco", "application/x-cocoa"};
        r0[39] = new String[]{".cdf", "application/x-netcdf"};
        r0[40] = new String[]{".cgi", "magnus-internal/cgi"};
        r0[41] = new String[]{".chat", "application/x-chat"};
        r0[42] = new String[]{".clp", "application/x-msclip"};
        r0[43] = new String[]{".cmx", "application/x-cmx"};
        r0[44] = new String[]{".co", "application/x-cult3d-object"};
        r0[45] = new String[]{".cod", "image/cis-cod"};
        r0[46] = new String[]{".cpio", "application/x-cpio"};
        r0[47] = new String[]{".cpt", "application/mac-compactpro"};
        r0[48] = new String[]{".crd", "application/x-mscardfile"};
        r0[49] = new String[]{".csh", "application/x-csh"};
        r0[50] = new String[]{".csm", "chemical/x-csml"};
        r0[51] = new String[]{".csml", "chemical/x-csml"};
        r0[52] = new String[]{".css", "text/css"};
        r0[53] = new String[]{".cur", "application/octet-stream"};
        r0[54] = new String[]{".doc", "application/msword"};
        r0[55] = new String[]{".docx", "application/msword"};
        r0[56] = new String[]{".dcm", "x-lml/x-evm"};
        r0[57] = new String[]{".dcr", "application/x-director"};
        r0[58] = new String[]{".dcx", "image/x-dcx"};
        r0[59] = new String[]{".dhtml", NanoHTTPD.MIME_HTML};
        r0[60] = new String[]{".dir", "application/x-director"};
        r0[61] = new String[]{".dll", "application/octet-stream"};
        r0[62] = new String[]{".dmg", "application/octet-stream"};
        r0[63] = new String[]{".dms", "application/octet-stream"};
        r0[64] = new String[]{".dot", "application/x-dot"};
        r0[65] = new String[]{".dvi", "application/x-dvi"};
        r0[66] = new String[]{".dwf", "drawing/x-dwf"};
        r0[67] = new String[]{".dwg", "application/x-autocad"};
        r0[68] = new String[]{".dxf", "application/x-autocad"};
        r0[69] = new String[]{".dxr", "application/x-director"};
        r0[70] = new String[]{".ebk", "application/x-expandedbook"};
        r0[71] = new String[]{".emb", "chemical/x-embl-dl-nucleotide"};
        r0[72] = new String[]{".embl", "chemical/x-embl-dl-nucleotide"};
        r0[73] = new String[]{".eps", "application/postscript"};
        r0[74] = new String[]{".epub", "application/epub+zip"};
        r0[75] = new String[]{".eri", "image/x-eri"};
        r0[76] = new String[]{".es", "audio/echospeech"};
        r0[77] = new String[]{".esl", "audio/echospeech"};
        r0[78] = new String[]{".etc", "application/x-earthtime"};
        r0[79] = new String[]{".etx", "text/x-setext"};
        r0[80] = new String[]{".evm", "x-lml/x-evm"};
        r0[81] = new String[]{".evy", "application/x-envoy"};
        r0[82] = new String[]{".exe", "application/octet-stream"};
        r0[83] = new String[]{".fh4", "image/x-freehand"};
        r0[84] = new String[]{".fh5", "image/x-freehand"};
        r0[85] = new String[]{".fhc", "image/x-freehand"};
        r0[86] = new String[]{".fif", "image/fif"};
        r0[87] = new String[]{".fm", "application/x-maker"};
        r0[88] = new String[]{".fpx", "image/x-fpx"};
        r0[89] = new String[]{".fvi", "video/isivideo"};
        r0[90] = new String[]{".flv", "video/x-msvideo"};
        r0[91] = new String[]{".gau", "chemical/x-gaussian-input"};
        r0[92] = new String[]{".gca", "application/x-gca-compressed"};
        r0[93] = new String[]{".gdb", "x-lml/x-gdb"};
        r0[94] = new String[]{".gif", "image/gif"};
        r0[95] = new String[]{".gps", "application/x-gps"};
        r0[96] = new String[]{".gtar", "application/x-gtar"};
        r0[97] = new String[]{".gz", "application/x-gzip"};
        r0[98] = new String[]{".gif", "image/gif"};
        r0[99] = new String[]{".gtar", "application/x-gtar"};
        r0[100] = new String[]{".gz", "application/x-gzip"};
        r0[101] = new String[]{".h", "text/plain"};
        r0[102] = new String[]{".hdf", "application/x-hdf"};
        r0[103] = new String[]{".hdm", "text/x-hdml"};
        r0[104] = new String[]{".hdml", "text/x-hdml"};
        r0[105] = new String[]{".htm", NanoHTTPD.MIME_HTML};
        r0[106] = new String[]{".html", NanoHTTPD.MIME_HTML};
        r0[107] = new String[]{".hlp", "application/winhlp"};
        r0[108] = new String[]{".hqx", "application/mac-binhex40"};
        r0[109] = new String[]{".hts", NanoHTTPD.MIME_HTML};
        r0[SoapEnvelope.VER11] = new String[]{".ice", "x-conference/x-cooltalk"};
        r0[111] = new String[]{".ico", "application/octet-stream"};
        r0[112] = new String[]{".ief", "image/ief"};
        r0[113] = new String[]{".ifm", "image/gif"};
        r0[114] = new String[]{".ifs", "image/ifs"};
        r0[115] = new String[]{".imy", "audio/melody"};
        r0[116] = new String[]{".ins", "application/x-net-install"};
        r0[117] = new String[]{".ips", "application/x-ipscript"};
        r0[118] = new String[]{".ipx", "application/x-ipix"};
        r0[119] = new String[]{".it", "audio/x-mod"};
        r0[SoapEnvelope.VER12] = new String[]{".itz", "audio/x-mod"};
        r0[121] = new String[]{".ivr", "i-world/i-vrml"};
        r0[122] = new String[]{".j2k", "image/j2k"};
        r0[123] = new String[]{".jad", "text/vnd.sun.j2me.app-descriptor"};
        r0[124] = new String[]{".jam", "application/x-jam"};
        r0[125] = new String[]{".jnlp", "application/x-java-jnlp-file"};
        r0[TransportMediator.KEYCODE_MEDIA_PLAY] = new String[]{".jpe", "image/jpeg"};
        r0[TransportMediator.KEYCODE_MEDIA_PAUSE] = new String[]{".jpz", "image/jpeg"};
        r0[128] = new String[]{".jwc", "application/jwc"};
        r0[129] = new String[]{".jar", "application/java-archive"};
        r0[130] = new String[]{".java", "text/plain"};
        r0[Wbxml.STR_T] = new String[]{".jpeg", "image/jpeg"};
        r0[Wbxml.LITERAL_A] = new String[]{".jpg", "image/jpeg"};
        r0[133] = new String[]{".js", "application/x-javascript"};
        r0[Font.e_fontCharsetGB2312] = new String[]{".kjx", "application/x-kjx"};
        r0[135] = new String[]{".lak", "x-lml/x-lak"};
        r0[Font.e_fontCharsetChineseBig5] = new String[]{".latex", "application/x-latex"};
        r0[137] = new String[]{".lcc", "application/fastman"};
        r0[138] = new String[]{".lcl", "application/x-digitalloca"};
        r0[139] = new String[]{".lcr", "application/x-digitalloca"};
        r0[140] = new String[]{".lgh", "application/lgh"};
        r0[141] = new String[]{".lha", "application/octet-stream"};
        r0[142] = new String[]{".lml", "x-lml/x-lml"};
        r0[143] = new String[]{".lmlpack", "x-lml/x-lmlpack"};
        r0[144] = new String[]{".log", "text/plain"};
        r0[145] = new String[]{".lsf", "video/x-ms-asf"};
        r0[146] = new String[]{".lsx", "video/x-ms-asf"};
        r0[147] = new String[]{".lzh", "application/x-lzh "};
        r0[148] = new String[]{".m13", "application/x-msmediaview"};
        r0[149] = new String[]{".m14", "application/x-msmediaview"};
        r0[150] = new String[]{".m15", "audio/x-mod"};
        r0[151] = new String[]{".m3u", "audio/x-mpegurl"};
        r0[CheckNewVersionThread2.MSG_TEXT] = new String[]{".m3url", "audio/x-mpegurl"};
        r0[CheckNewVersionThread2.MSG_CREATEPROGRESS] = new String[]{".ma1", "audio/ma1"};
        r0[154] = new String[]{".ma2", "audio/ma2"};
        r0[155] = new String[]{".ma3", "audio/ma3"};
        r0[156] = new String[]{".ma5", "audio/ma5"};
        r0[157] = new String[]{".man", "application/x-troff-man"};
        r0[158] = new String[]{".map", "magnus-internal/imagemap"};
        r0[159] = new String[]{".mbd", "application/mbedlet"};
        r0[ThumbnailUtils.TARGET_SIZE_MICRO_THUMBNAIL_HEIGHT] = new String[]{".mct", "application/x-mascot"};
        r0[Font.e_fontCharsetGreek] = new String[]{".mdb", "application/x-msaccess"};
        r0[Font.e_fontCharsetTurkish] = new String[]{".mdz", "audio/x-mod"};
        r0[163] = new String[]{".me", "application/x-troff-me"};
        r0[164] = new String[]{".mel", "text/x-vmel"};
        r0[165] = new String[]{".mi", "application/x-mif"};
        r0[166] = new String[]{".mid", "audio/midi"};
        r0[167] = new String[]{".midi", "audio/midi"};
        r0[168] = new String[]{".m4a", "audio/mp4a-latm"};
        r0[169] = new String[]{".m4b", "audio/mp4a-latm"};
        r0[170] = new String[]{".m4p", "audio/mp4a-latm"};
        r0[171] = new String[]{".m4u", "video/vnd.mpegurl"};
        r0[172] = new String[]{".m4v", "video/x-m4v"};
        r0[173] = new String[]{".mov", "video/quicktime"};
        r0[174] = new String[]{".mp2", "audio/x-mpeg"};
        r0[175] = new String[]{".mp3", "audio/x-mpeg"};
        r0[176] = new String[]{".mp4", "video/mp4"};
        r0[Font.e_fontCharsetHebrew] = new String[]{".mpc", "application/vnd.mpohun.certificate"};
        r0[Font.e_fontCharsetArabic] = new String[]{".mpe", "video/mpeg"};
        r0[179] = new String[]{".mpeg", "video/mpeg"};
        r0[180] = new String[]{".mpg", "video/mpeg"};
        r0[181] = new String[]{".mpg4", "video/mp4"};
        r0[182] = new String[]{".mpga", "audio/mpeg"};
        r0[ErrorCode.ERROR_ALREADY_EXISTS] = new String[]{".msg", "application/vnd.ms-outlook"};
        r0[184] = new String[]{".mif", "application/x-mif"};
        r0[185] = new String[]{".mil", "image/x-cals"};
        r0[Font.e_fontCharsetBaltic] = new String[]{".mio", "audio/x-mio"};
        r0[187] = new String[]{".mmf", "application/x-skt-lbs"};
        r0[188] = new String[]{".mng", "video/x-mng"};
        r0[189] = new String[]{".mny", "application/x-msmoney"};
        r0[190] = new String[]{".moc", "application/x-mocha"};
        r0[191] = new String[]{".mocha", "application/x-mocha"};
        r0[Wbxml.EXT_0] = new String[]{".mod", "audio/x-mod"};
        r0[Wbxml.EXT_1] = new String[]{".mof", "application/x-yumekara"};
        r0[Wbxml.EXT_2] = new String[]{".mol", "chemical/x-mdl-molfile"};
        r0[Wbxml.OPAQUE] = new String[]{".mop", "chemical/x-mopac-input"};
        r0[Wbxml.LITERAL_AC] = new String[]{".movie", "video/x-sgi-movie"};
        r0[197] = new String[]{".mpn", "application/vnd.mophun.application"};
        r0[BuildConfig.VERSION_CODE] = new String[]{".mpp", "application/vnd.ms-project"};
        r0[199] = new String[]{".mps", "application/x-mapserver"};
        r0[200] = new String[]{".mrl", "text/x-mrml"};
        r0[HttpStatus.SC_CREATED] = new String[]{".mrm", "application/x-mrm"};
        r0[HttpStatus.SC_ACCEPTED] = new String[]{".ms", "application/x-troff-ms"};
        r0[HttpStatus.SC_NON_AUTHORITATIVE_INFORMATION] = new String[]{".mts", "application/metastream"};
        r0[204] = new String[]{".mtx", "application/metastream"};
        r0[HttpStatus.SC_RESET_CONTENT] = new String[]{".mtz", "application/metastream"};
        r0[HttpStatus.SC_PARTIAL_CONTENT] = new String[]{".mzv", "application/metastream"};
        r0[HttpStatus.SC_MULTI_STATUS] = new String[]{".nar", "application/zip"};
        r0[208] = new String[]{".nbmp", "image/nbmp"};
        r0[209] = new String[]{".nc", "application/x-netcdf"};
        r0[210] = new String[]{".ndb", "x-lml/x-ndb"};
        r0[211] = new String[]{".ndwn", "application/ndwn"};
        r0[ThumbnailUtils.TARGET_SIZE_MICRO_THUMBNAIL_WIDTH] = new String[]{".nif", "application/x-nif"};
        r0[213] = new String[]{".nmz", "application/x-scream"};
        r0[214] = new String[]{".nokia-op-logo", "image/vnd.nok-oplogo-color"};
        r0[215] = new String[]{".npx", "application/x-netfpx"};
        r0[216] = new String[]{".nsnd", "audio/nsnd"};
        r0[217] = new String[]{".nva", "application/x-neva1"};
        r0[218] = new String[]{".oda", "application/oda"};
        r0[219] = new String[]{".oom", "application/x-atlasMate-plugin"};
        r0[220] = new String[]{".ogg", "audio/ogg"};
        r0[221] = new String[]{".pac", "audio/x-pac"};
        r0[Font.e_fontCharsetThai] = new String[]{".pae", "audio/x-epac"};
        r0[223] = new String[]{".pan", "application/x-pan"};
        r0[224] = new String[]{".pbm", "image/x-portable-bitmap"};
        r0[225] = new String[]{".pcx", "image/x-pcx"};
        r0[226] = new String[]{".pda", "image/x-pda"};
        r0[227] = new String[]{".pdb", "chemical/x-pdb"};
        r0[228] = new String[]{".pdf", "application/pdf"};
        r0[229] = new String[]{".ppdf", "text/plain"};
        r0[230] = new String[]{".ofd", "text/plain"};
        r0[231] = new String[]{".pfr", "application/font-tdpfr"};
        r0[232] = new String[]{".pgm", "image/x-portable-graymap"};
        r0[233] = new String[]{".pict", "image/x-pict"};
        r0[234] = new String[]{".pm", "application/x-perl"};
        r0[235] = new String[]{".pmd", "application/x-pmd"};
        r0[236] = new String[]{".png", "image/png"};
        r0[237] = new String[]{".pnm", "image/x-portable-anymap"};
        r0[Font.e_fontCharsetEastEurope] = new String[]{".pnz", "image/png"};
        r0[239] = new String[]{".pot", "application/vnd.ms-powerpoint"};
        r0[240] = new String[]{".ppm", "image/x-portable-pixmap"};
        r0[241] = new String[]{".pps", "application/vnd.ms-powerpoint"};
        r0[242] = new String[]{".ppt", "application/vnd.ms-powerpoint"};
        r0[243] = new String[]{".pptx", "application/vnd.ms-powerpoint"};
        r0[244] = new String[]{".pqf", "application/x-cprplayer"};
        r0[245] = new String[]{".pqi", "application/cprplayer"};
        r0[246] = new String[]{".prc", "application/x-prc"};
        r0[247] = new String[]{".proxy", "application/x-ns-proxy-autoconfig"};
        r0[248] = new String[]{".prop", "text/plain"};
        r0[249] = new String[]{".ps", "application/postscript"};
        r0[250] = new String[]{".ptlk", "application/listenup"};
        r0[251] = new String[]{".pub", "application/x-mspublisher"};
        r0[252] = new String[]{".pvx", "video/x-pv-pvx"};
        r0[253] = new String[]{".qcp", "audio/vnd.qcelp"};
        r0[254] = new String[]{".qt", "video/quicktime"};
        r0[255] = new String[]{".qti", "image/x-quicktime"};
        r0[256] = new String[]{".qtif", "image/x-quicktime"};
        r0[257] = new String[]{".r3t", "text/vnd.rn-realtext3d"};
        r0[258] = new String[]{".ra", "audio/x-pn-realaudio"};
        r0[259] = new String[]{".ram", "audio/x-pn-realaudio"};
        r0[260] = new String[]{".ras", "image/x-cmu-raster"};
        r0[261] = new String[]{".rdf", "application/rdf+xml"};
        r0[262] = new String[]{".rf", "image/vnd.rn-realflash"};
        r0[263] = new String[]{".rgb", "image/x-rgb"};
        r0[264] = new String[]{".rlf", "application/x-richlink"};
        r0[265] = new String[]{".rm", "audio/x-pn-realaudio"};
        r0[266] = new String[]{".rmf", "audio/x-rmf"};
        r0[267] = new String[]{".rmm", "audio/x-pn-realaudio"};
        r0[268] = new String[]{".rnx", "application/vnd.rn-realplayer"};
        r0[269] = new String[]{".roff", "application/x-troff"};
        r0[270] = new String[]{".rp", "image/vnd.rn-realpix"};
        r0[271] = new String[]{".rpm", "audio/x-pn-realaudio-plugin"};
        r0[272] = new String[]{".rt", "text/vnd.rn-realtext"};
        r0[273] = new String[]{".rte", "x-lml/x-gps"};
        r0[274] = new String[]{".rtf", "application/rtf"};
        r0[275] = new String[]{".rtg", "application/metastream"};
        r0[276] = new String[]{".rtx", "text/richtext"};
        r0[277] = new String[]{".rv", "video/vnd.rn-realvideo"};
        r0[278] = new String[]{".rwc", "application/x-rogerwilco"};
        r0[279] = new String[]{".rar", "application/x-rar-compressed"};
        r0[280] = new String[]{".rc", "text/plain"};
        r0[281] = new String[]{".rmvb", "audio/x-pn-realaudio"};
        r0[282] = new String[]{".s3m", "audio/x-mod"};
        r0[283] = new String[]{".s3z", "audio/x-mod"};
        r0[284] = new String[]{".sca", "application/x-supercard"};
        r0[285] = new String[]{".scd", "application/x-msschedule"};
        r0[286] = new String[]{".sdf", "application/e-score"};
        r0[287] = new String[]{".sea", "application/x-stuffit"};
        r0[288] = new String[]{".sgm", "text/x-sgml"};
        r0[289] = new String[]{".sgml", "text/x-sgml"};
        r0[290] = new String[]{".shar", "application/x-shar"};
        r0[291] = new String[]{".shtml", "magnus-internal/parsed-html"};
        r0[292] = new String[]{".shw", "application/presentations"};
        r0[293] = new String[]{".si6", "image/si6"};
        r0[294] = new String[]{".si7", "image/vnd.stiwap.sis"};
        r0[295] = new String[]{".si9", "image/vnd.lgtwap.sis"};
        r0[296] = new String[]{".sis", "application/vnd.symbian.install"};
        r0[297] = new String[]{".sit", "application/x-stuffit"};
        r0[298] = new String[]{".skd", "application/x-koan"};
        r0[299] = new String[]{".skm", "application/x-koan"};
        r0[HttpStatus.SC_MULTIPLE_CHOICES] = new String[]{".skp", "application/x-koan"};
        r0[HttpStatus.SC_MOVED_PERMANENTLY] = new String[]{".skt", "application/x-koan"};
        r0[HttpStatus.SC_MOVED_TEMPORARILY] = new String[]{".slc", "application/x-salsa"};
        r0[HttpStatus.SC_SEE_OTHER] = new String[]{".smd", "audio/x-smd"};
        r0[HttpStatus.SC_NOT_MODIFIED] = new String[]{".smi", "application/smil"};
        r0[HttpStatus.SC_USE_PROXY] = new String[]{".smil", "application/smil"};
        r0[306] = new String[]{".smp", "application/studiom"};
        r0[307] = new String[]{".smz", "audio/x-smd"};
        r0[StatusLine.HTTP_PERM_REDIRECT] = new String[]{".sh", "application/x-sh"};
        r0[309] = new String[]{".snd", "audio/basic"};
        r0[310] = new String[]{".spc", "text/x-speech"};
        r0[311] = new String[]{".spl", "application/futuresplash"};
        r0[312] = new String[]{".spr", "application/x-sprite"};
        r0[313] = new String[]{".sprite", "application/x-sprite"};
        r0[314] = new String[]{".sdp", "application/sdp"};
        r0[315] = new String[]{".spt", "application/x-spt"};
        r0[316] = new String[]{".src", "application/x-wais-source"};
        r0[317] = new String[]{".stk", "application/hyperstudio"};
        r0[318] = new String[]{".stm", "audio/x-mod"};
        r0[319] = new String[]{".sv4cpio", "application/x-sv4cpio"};
        r0[ThumbnailUtils.TARGET_SIZE_MINI_THUMBNAIL_HEIGHT] = new String[]{".sv4crc", "application/x-sv4crc"};
        r0[321] = new String[]{".svf", "image/vnd"};
        r0[322] = new String[]{".svg", "image/svg-xml"};
        r0[323] = new String[]{".svh", "image/svh"};
        r0[324] = new String[]{".svr", "x-world/x-svr"};
        r0[325] = new String[]{".swf", "application/x-shockwave-flash"};
        r0[326] = new String[]{".swfl", "application/x-shockwave-flash"};
        r0[327] = new String[]{".t", "application/x-troff"};
        r0[328] = new String[]{".tad", "application/octet-stream"};
        r0[329] = new String[]{".talk", "text/x-speech"};
        r0[330] = new String[]{".tar", "application/x-tar"};
        r0[331] = new String[]{".taz", "application/x-tar"};
        r0[332] = new String[]{".tbp", "application/x-timbuktu"};
        r0[333] = new String[]{".tbt", "application/x-timbuktu"};
        r0[334] = new String[]{".tcl", "application/x-tcl"};
        r0[335] = new String[]{".tex", "application/x-tex"};
        r0[336] = new String[]{".texi", "application/x-texinfo"};
        r0[337] = new String[]{".texinfo", "application/x-texinfo"};
        r0[338] = new String[]{".tgz", "application/x-tar"};
        r0[339] = new String[]{".thm", "application/vnd.eri.thm"};
        r0[340] = new String[]{".tif", "image/tiff"};
        r0[341] = new String[]{".tiff", "image/tiff"};
        r0[342] = new String[]{".tki", "application/x-tkined"};
        r0[343] = new String[]{".tkined", "application/x-tkined"};
        r0[344] = new String[]{".toc", "application/toc"};
        r0[345] = new String[]{".toy", "image/toy"};
        r0[346] = new String[]{".tr", "application/x-troff"};
        r0[347] = new String[]{".trk", "x-lml/x-gps"};
        r0[348] = new String[]{".trm", "application/x-msterminal"};
        r0[349] = new String[]{".tsi", "audio/tsplayer"};
        r0[350] = new String[]{".tsp", "application/dsptype"};
        r0[351] = new String[]{".tsv", "text/tab-separated-values"};
        r0[352] = new String[]{".ttf", "application/octet-stream"};
        r0[353] = new String[]{".ttz", "application/t-time"};
        r0[354] = new String[]{".txt", "text/plain"};
        r0[355] = new String[]{".ult", "audio/x-mod"};
        r0[356] = new String[]{".ustar", "application/x-ustar"};
        r0[357] = new String[]{".uu", "application/x-uuencode"};
        r0[358] = new String[]{".uue", "application/x-uuencode"};
        r0[359] = new String[]{".vcd", "application/x-cdlink"};
        r0[360] = new String[]{".vcf", "text/x-vcard"};
        r0[361] = new String[]{".vdo", "video/vdo"};
        r0[362] = new String[]{".vib", "audio/vib"};
        r0[363] = new String[]{".viv", "video/vivo"};
        r0[364] = new String[]{".vivo", "video/vivo"};
        r0[365] = new String[]{".vmd", "application/vocaltec-media-desc"};
        r0[366] = new String[]{".vmf", "application/vocaltec-media-file"};
        r0[367] = new String[]{".vmi", "application/x-dreamcast-vms-info"};
        r0[368] = new String[]{".vms", "application/x-dreamcast-vms"};
        r0[369] = new String[]{".vox", "audio/voxware"};
        r0[370] = new String[]{".vqe", "audio/x-twinvq-plugin"};
        r0[371] = new String[]{".vqf", "audio/x-twinvq"};
        r0[372] = new String[]{".vql", "audio/x-twinvq"};
        r0[373] = new String[]{".vre", "x-world/x-vream"};
        r0[374] = new String[]{".vrml", "x-world/x-vrml"};
        r0[375] = new String[]{".vrt", "x-world/x-vrt"};
        r0[376] = new String[]{".vrw", "x-world/x-vream"};
        r0[377] = new String[]{".vts", "workbook/formulaone"};
        r0[378] = new String[]{".wax", "audio/x-ms-wax"};
        r0[379] = new String[]{".wbmp", "image/vnd.wap.wbmp"};
        r0[380] = new String[]{".web", "application/vnd.xara"};
        r0[381] = new String[]{".wav", "audio/x-wav"};
        r0[382] = new String[]{".wma", "audio/x-ms-wma"};
        r0[383] = new String[]{".wmv", "audio/x-ms-wmv"};
        r0[384] = new String[]{".wi", "image/wavelet"};
        r0[385] = new String[]{".wis", "application/x-InstallShield"};
        r0[386] = new String[]{".wm", "video/x-ms-wm"};
        r0[387] = new String[]{".wmd", "application/x-ms-wmd"};
        r0[388] = new String[]{".wmf", "application/x-msmetafile"};
        r0[389] = new String[]{".wml", "text/vnd.wap.wml"};
        r0[390] = new String[]{".wmlc", "application/vnd.wap.wmlc"};
        r0[391] = new String[]{".wmls", "text/vnd.wap.wmlscript"};
        r0[392] = new String[]{".wmlsc", "application/vnd.wap.wmlscriptc"};
        r0[393] = new String[]{".wmlscript", "text/vnd.wap.wmlscript"};
        r0[394] = new String[]{".wmv", "video/x-ms-wmv"};
        r0[395] = new String[]{".wmx", "video/x-ms-wmx"};
        r0[396] = new String[]{".wmz", "application/x-ms-wmz"};
        r0[397] = new String[]{".wpng", "image/x-up-wpng"};
        r0[398] = new String[]{".wps", "application/vnd.ms-works"};
        r0[399] = new String[]{".wpt", "x-lml/x-gps"};
        r0[HttpStatus.SC_BAD_REQUEST] = new String[]{".wri", "application/x-mswrite"};
        r0[HttpStatus.SC_UNAUTHORIZED] = new String[]{".wrl", "x-world/x-vrml"};
        r0[HttpStatus.SC_PAYMENT_REQUIRED] = new String[]{".wrz", "x-world/x-vrml"};
        r0[HttpStatus.SC_FORBIDDEN] = new String[]{".ws", "text/vnd.wap.wmlscript"};
        r0[HttpStatus.SC_NOT_FOUND] = new String[]{".wsc", "application/vnd.wap.wmlscriptc"};
        r0[HttpStatus.SC_METHOD_NOT_ALLOWED] = new String[]{".wv", "video/wavelet"};
        r0[HttpStatus.SC_NOT_ACCEPTABLE] = new String[]{".wvx", "video/x-ms-wvx"};
        r0[HttpStatus.SC_PROXY_AUTHENTICATION_REQUIRED] = new String[]{".wxl", "application/x-wxl"};
        r0[HttpStatus.SC_REQUEST_TIMEOUT] = new String[]{".x-gzip", "application/x-gzip"};
        r0[HttpStatus.SC_CONFLICT] = new String[]{".xar", "application/vnd.xara"};
        r0[HttpStatus.SC_GONE] = new String[]{".xbm", "image/x-xbitmap"};
        r0[HttpStatus.SC_LENGTH_REQUIRED] = new String[]{".xdm", "application/x-xdma"};
        r0[HttpStatus.SC_PRECONDITION_FAILED] = new String[]{".xdma", "application/x-xdma"};
        r0[HttpStatus.SC_REQUEST_TOO_LONG] = new String[]{".xdw", "application/vnd.fujixerox.docuworks"};
        r0[HttpStatus.SC_REQUEST_URI_TOO_LONG] = new String[]{".xht", "application/xhtml+xml"};
        r0[HttpStatus.SC_UNSUPPORTED_MEDIA_TYPE] = new String[]{".xhtm", "application/xhtml+xml"};
        r0[HttpStatus.SC_REQUESTED_RANGE_NOT_SATISFIABLE] = new String[]{".xhtml", "application/xhtml+xml"};
        r0[HttpStatus.SC_EXPECTATION_FAILED] = new String[]{".xla", "application/vnd.ms-excel"};
        r0[418] = new String[]{".xlc", "application/vnd.ms-excel"};
        r0[HttpStatus.SC_INSUFFICIENT_SPACE_ON_RESOURCE] = new String[]{".xll", "application/x-excel"};
        r0[HttpStatus.SC_METHOD_FAILURE] = new String[]{".xlm", "application/vnd.ms-excel"};
        r0[421] = new String[]{".xls", "application/vnd.ms-excel"};
        r0[HttpStatus.SC_UNPROCESSABLE_ENTITY] = new String[]{".xlsx", "application/vnd.ms-excel"};
        r0[HttpStatus.SC_LOCKED] = new String[]{".xlt", "application/vnd.ms-excel"};
        r0[HttpStatus.SC_FAILED_DEPENDENCY] = new String[]{".xlw", "application/vnd.ms-excel"};
        r0[425] = new String[]{".xm", "audio/x-mod"};
        r0[ThumbnailUtils.TARGET_SIZE_MINI_THUMBNAIL_WIDTH] = new String[]{".xml", "text/xml"};
        r0[427] = new String[]{".xmz", "audio/x-mod"};
        r0[428] = new String[]{".xpi", "application/x-xpinstall"};
        r0[429] = new String[]{".xpm", "image/x-xpixmap"};
        r0[430] = new String[]{".xsit", "text/xml"};
        r0[431] = new String[]{".xsl", "text/xml"};
        r0[432] = new String[]{".xul", "text/xul"};
        r0[433] = new String[]{".xwd", "image/x-xwindowdump"};
        r0[434] = new String[]{".xyz", "chemical/x-pdb"};
        r0[435] = new String[]{".yz1", "application/x-yz1"};
        r0[436] = new String[]{".z", "application/x-compress"};
        r0[437] = new String[]{".zac", "application/x-zaurus-zac"};
        r0[438] = new String[]{".zip", "application/zip"};
        r0[439] = new String[]{"", "*/*"};
        MIME_MapTable = r0;
    }
}
